{
 "title": "General Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Database", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Organization Accunts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Accounts in Organization\" from account where account.foreign=0;"
    }
   ]
  },
  {
   "title": "Total Policies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(policy.id) from policy;"
    }
   ]
  },
  {
   "title": "Policies by Scope",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select now() as time , scope, count(id) from policy group by scope;"
    },
    {
     "rawSql": "select now() as time, sum(inline_count) as \"Inline Role\" from role where inline_count > 0;"
    },
    {
     "rawSql": "select now() as time, sum(inline_count) as \"Inline User\" from user where inline_count > 0;"
    }
   ]
  },
  {
   "title": "Policies by Attachment",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select now() as time , count(id) as \"Attached to more than 1 Role\" from policy where attachment_count>1;"
    },
    {
     "rawSql": "select now() as time , count(id) as \"Attached only to 1 entity\" from policy where attachment_count=1;"
    }
   ]
  },
  {
   "title": "Top 15 Policies in accounts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select acc.name as Name , count(ro.arn) as Value from policy as ro inner join account as acc on acc.id=ro.account_id where acc.foreign=0 group by ro.account_id order by count(ro.arn) desc limit 10;"
    }
   ]
  },
  {
   "title": "Total Roles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(role.id) from role where role.foreign=0;"
    }
   ]
  },
  {
   "title": "Roles with more than one policy",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select now() as time, count(a.count) as \"<=1 Policy\" from (select count(policy_id) as \"count\" from role_policy group by role_id) as a where a.count<=1"
    },
    {
     "rawSql": "select now() as time, count(a.count) as \">1 Policies\" from (select count(policy_id) as \"count\" from role_policy group by role_id) as a where a.count>1"
    }
   ]
  },
  {
   "title": "Roles in accounts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select acc.name as Name , count(ro.arn) as Value from role as ro inner join account as acc on acc.id=ro.account_id where acc.foreign=0 group by ro.account_id order by count(ro.arn) desc limit 15;"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from user where user.foreign=0;"
    }
   ]
  },
  {
   "title": "Users in accounts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select acc.name as Name , count(ro.arn) as Value from user as ro inner join account as acc on acc.id=ro.account_id where acc.foreign=0 group by ro.account_id order by count(ro.arn) desc limit 20;"
    }
   ]
  },
  {
   "title": "Roles created by time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short", "label": "Accounts" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  role.create_date AS \"time\",\n  role.name AS metric,\n  cast(acc.uuid as unsigned)\nFROM role inner join account as acc on acc.id=role.account_id\nWHERE\n  $__timeFilter(create_date)\nORDER BY create_date"
    }
   ]
  },
  {
   "title": "Foreign",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "Total Foreign Accounts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Foreign\" from account where account.foreign=1 and blacklisted=0;"
    }
   ]
  },
  {
   "title": "Foreign accounts",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 41 },
   "targets": [
    {
     "rawSql": "select uuid as \"Account number\" from account where account.foreign=1 and account.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Total Foreign Roles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(ro.arn) as Value from role as ro inner join account as acc on acc.id=ro.account_id where acc.foreign=1 and acc.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Foreign Roles",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 41 },
   "targets": [
    {
     "rawSql": "select distinct role.arn as \"Role Arn\", account.uuid as \"Account\" from role inner join trusted_role_role as ta on ta.assuming_role_id=role.id inner join account on role.account_id=account.id where role.foreign=1 and account.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Foreign users",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 46 },
   "targets": [
    {
     "rawSql": "select distinct user.arn as \"User Arn\", account.uuid as \"Account\" from user inner join trusted_role_user as ta on ta.user_id=user.id inner join account on user.account_id=account.id where user.foreign=1 and account.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Total Foreign accounts (Full Access)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct a.id) as \"Foreign Accounts\" from account as a inner join trusted_role_account as ta on a.id=ta.account_id where a.foreign=1 and a.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Foreign (Full Access) accounts",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 47 },
   "targets": [
    {
     "rawSql": "select distinct account.uuid as \"Account number\" from account inner join trusted_role_account as ta on ta.account_id=account.id where account.foreign=1 and account.blacklisted=0;"
    }
   ]
  },
  {
   "title": "Total Foreign Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(ro.arn) as Value from user as ro inner join account as acc on acc.id=ro.account_id where acc.foreign=1 and acc.blacklisted=0;"
    }
   ]
  }
 ]
}