{
 "title": "KPI Dashboards",
 "time": { "from": "2020-08-31T12:01:31.523Z", "to": "2020-09-01T00:01:31.523Z" },
 "templating": {
  "list": [
   { "name": "Database", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:80px; text-align: center;\"><img style=\"height:150px;\" src=\"https://i.imgur.com/nUSa44U.png\"/ > Key Performance Indicators</p>"
   }
  },
  {
   "title": "Cantidad de Roles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "select count(*) from role" }
   ]
  },
  {
   "title": "Cantidad de Polcies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "select count(*) from policy" }
   ]
  },
  {
   "title": "Top Roles with more Trusted Entities ",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 9, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select ro.name,\n       count(distinct ta.account_id) + count( distinct tu.user_id) + count(distinct ts.service_id) + count(distinct tr.assuming_role_id) as \"Total\"\nfrom role as ro\n         left join trusted_role_account as ta on ta.role_id = ro.id\n         left join trusted_role_user as tu on tu.role_id = ro.id\n         left join trusted_role_service as ts on ts.role_id = ro.id\n         left join trusted_role_role as tr on tr.role_id = ro.id\ngroup by ro.name\norder by Total desc limit 30"
    }
   ]
  },
  {
   "title": "Role by service",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name as \"Service\", count(distinct role.arn)\nfrom service\n         left join permission on permission.service_id = service.id\n         left join policy on policy.id = permission.policy_id\n         left join role_policy on policy.id = role_policy.policy_id\n         left join role on role.id = role_policy.role_id\ngroup by service.name\norder by count(distinct role.arn) desc limit 20"
    }
   ]
  },
  {
   "title": "Roles without use",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() as time, count(distinct ro.id) as \"Without use\"\nfrom role as ro\nwhere last_used <= (NOW() - INTERVAL 90 DAY)\n   OR last_used is null;"
    },
    {
     "rawSql": "select NOW()                                    as time,\n       count(ro.id) - (select count(distinct ro.id)\n                       from role as ro\n                       where last_used <= (NOW() - INTERVAL 90 DAY)\n                          OR last_used is null) as \"Being used\"\nfrom role as ro;\n"
    }
   ]
  },
  {
   "title": "Policies without use",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, count(distinct pe.policy_id) as \"Without use\" from permission as pe where last_used < (NOW() - INTERVAL 90 DAY) or last_used is null;"
    },
    {
     "rawSql": "select now() as time, count(distinct pe.policy_id) - (select count(distinct pe.policy_id) from permission as pe where last_used < (NOW() - INTERVAL 90 DAY) or last_used is null) as \"Being used\" from permission as pe;\n"
    }
   ]
  },
  {
   "title": "Roles that trust external entities",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct ro.arn) from role as ro left join trusted_role_account as ta on ta.role_id = ro.id\n\tleft join trusted_role_user as tu on tu.role_id = ro.id\n                                            left join trusted_role_role as tr on tr.role_id = ro.id\n                                        left join account on account.id = ta.account_id\n                                        left join user on user.id = tu.user_id\n                               where account.foreign = 1 or user.foreign = 1 or ro.foreign = 1 and account.blacklisted = 0"
    }
   ]
  },
  {
   "title": "External Roles compliant",
   "type": "grafana-piechart-panel",
   "description": "This pie chart show which Roles are complaint (have an externalId set) from those Role that can be assumed from external entities.\n",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time , count(id) as \"External Trust Compliant\" from (select distinct ro.arn as tarn\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where (account.foreign = 1 or user.foreign = 1 or ro.foreign = 1) and account.blacklisted = 0) as trusty left join role on role.arn=trusty.tarn where ext_entity_compliance=1;"
    },
    {
     "rawSql": "select now() as time , count(id) as \"Not External Trust Compliant\" from (select distinct ro.arn as tarn\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where (account.foreign = 1 or user.foreign = 1 or ro.foreign = 1) and account.blacklisted = 0) as trusty left join role on role.arn=trusty.tarn where ext_entity_compliance=0;"
    }
   ]
  },
  {
   "title": "Roles that trust external entities",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select ro.arn,\n                   count(distinct ta.account_id) + count( distinct tu.user_id) + count(distinct tr.assuming_role_id) as \"Total\"\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where account.foreign = 1 or user.foreign = 1 or ro.foreign = 1 and account.blacklisted = 0\n            group by ro.arn\n            order by Total desc"
    }
   ]
  },
  {
   "title": "Cuentas que pueden ser accedidas por entidades externas",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "rawSql": "select distinct account.uuid, account.name from (select ro.arn,\n                   count(distinct ta.account_id) + count( distinct tu.user_id) + count(distinct tr.assuming_role_id) as \"Total\"\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where account.foreign = 1 or user.foreign = 1 or ro.foreign = 1 and account.blacklisted = 0\n            group by ro.arn\n            order by Total desc) as asd inner join role on role.arn=asd.arn inner join account on role.account_id=account.id"
    }
   ]
  },
  {
   "title": "Roles that trust external entities with lastUsed",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "select ro.arn, DATEDIFF(NOW(), ro.last_used) as last_used\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where (account.foreign = 1 or user.foreign = 1 or ro.foreign = 1) and account.blacklisted = 0 and (DATEDIFF(NOW(), ro.last_used) > 90 or ro.last_used is null)\n            order by last_used desc"
    }
   ]
  },
  {
   "title": "Roles that trust external entities without ExternalID",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "select distinct ro.arn, DATEDIFF(NOW(), ro.last_used) as last_used\n            from role as ro\n                     left join trusted_role_account as ta on ta.role_id = ro.id\n                     left join trusted_role_user as tu on tu.role_id = ro.id\n                     left join trusted_role_role as tr on tr.role_id = ro.id\n                     left join account on account.id = ta.account_id\n                     left join user on user.id = tu.user_id\n            where (account.foreign = 1 or user.foreign = 1 or ro.foreign = 1) and account.blacklisted = 0 and ro.ext_entity_compliance=0\n            order by last_used desc"
    }
   ]
  }
 ]
}