{
 "title": "Polp Accounts",
 "description": "Corte por cuenta",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Database", "query": "mysql" },
   {
    "name": "acc",
    "label": "Account:",
    "query": "select id as __value , name as __text from account where `foreign`!=1;"
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "stat",
   "description": "Total ammount of policies",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Service count\" from service;"
    }
   ]
  },
  {
   "title": "Top Services with more policies in $acc",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, count(permission.policy_id) as \"Policies in Services\" from service inner join permission on permission.service_id=service.id inner join policy on policy.id=permission.policy_id where policy.account_id=\"$acc\" group by service.name order by count(permission.policy_id) desc;"
    }
   ]
  },
  { "title": "Policies (Attached only) ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Policies in $acc",
   "type": "stat",
   "description": "Total ammount of policies",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Policy count\" from policy where policy.account_id=\"$acc\";"
    }
   ]
  },
  {
   "title": "TOP 10 Policies with access to services  ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 10, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select po.name as policy, count(distinct pe.service_id) as service_cant from permission as pe inner join policy as po on pe.policy_id=po.id where po.account_id=\"$acc\" and po.scope != \"AWS\" group by po.arn order by count(pe.service_id) desc limit 20;"
    }
   ]
  },
  {
   "title": "TOP 20 Polices by attachment ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select name, attachment_count from policy where account_id=\"$acc\" order by attachment_count desc limit 20;"
    }
   ]
  },
  {
   "title": "Policies Scope  ($acc)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select now() as time , scope, count(id) from policy where account_id=\"$acc\" group by scope;"
    }
   ]
  },
  {
   "title": "Customer Policies in $acc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Customer Managed\" from policy where policy.scope = 'Local' and policy.account_id=\"$acc\";"
    }
   ]
  },
  {
   "title": "Managed Policies in $acc",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as 'AWS Managed' from policy where policy.scope = 'AWS' and policy.account_id=\"$acc\";"
    }
   ]
  },
  {
   "title": "Actions ",
   "type": "snuids-radar-panel",
   "description": "This metrics displays actions occurrences in services .",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select now() as time , name, sum(tagging) from permission inner join service on service.id=permission.service_id where service.name in (\"ec2\",\"s3\",\"cloudwatch\",\"iam\",\"rds\",\"dynamodb\")  group by service.name order by sum(tagging);"
    },
    {
     "rawSql": "select now() as time , name, sum(managing) from permission inner join service on service.id=permission.service_id where service.name in (\"ec2\",\"s3\",\"cloudwatch\",\"iam\",\"rds\",\"dynamodb\")  group by service.name order by sum(managing);"
    },
    {
     "rawSql": "select now() as time , name, sum(writing) from permission inner join service on service.id=permission.service_id where service.name in (\"ec2\",\"s3\",\"cloudwatch\",\"iam\",\"rds\", \"dynamodb\")  group by service.name order by sum(writing);"
    },
    {
     "rawSql": "select now() as time , name, sum(listing) from permission inner join service on service.id=permission.service_id where service.name in (\"ec2\",\"s3\",\"cloudwatch\",\"iam\",\"rds\",\"dynamodb\")  group by service.name order by sum(listing);"
    },
    {
     "rawSql": "select now() as time , name, sum(reading) from permission inner join service on service.id=permission.service_id where service.name in (\"ec2\",\"s3\",\"cloudwatch\",\"iam\",\"rds\",\"dynamodb\")  group by service.name order by sum(reading);"
    }
   ]
  },
  {
   "title": "Reading",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, sum(reading) from permission inner join service on service.id=permission.service_id inner join policy on permission.policy_id=policy.id where policy.account_id=\"$acc\" group by service.name order by sum(reading) desc limit 10;"
    }
   ]
  },
  {
   "title": "Write",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, sum(writing) from permission inner join service on service.id=permission.service_id inner join policy on permission.policy_id=policy.id where policy.account_id=\"$acc\" group by service.name order by sum(writing) desc limit 10;"
    }
   ]
  },
  {
   "title": "Tagging",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, sum(tagging) from permission inner join service on service.id=permission.service_id inner join policy on permission.policy_id=policy.id where policy.account_id=\"$acc\" group by service.name order by sum(tagging) desc limit 10;"
    }
   ]
  },
  {
   "title": "Listing",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, sum(listing) from permission inner join service on service.id=permission.service_id inner join policy on permission.policy_id=policy.id where policy.account_id=\"$acc\" group by service.name order by sum(listing) desc limit 10;"
    }
   ]
  },
  {
   "title": "Managing",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name, sum(managing) from permission inner join service on service.id=permission.service_id inner join policy on permission.policy_id=policy.id where policy.account_id=\"$acc\" group by service.name order by sum(managing) desc limit 10;"
    }
   ]
  },
  { "title": "Roles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Roles   ($acc)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from role where account_id=\"$acc\";"
    }
   ]
  },
  {
   "title": "Top Roles with more Policies ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select r.name as role_name, count(p.name) as policy_cant from role as r inner join role_policy as rp on r.id = rp.role_id inner join policy as p on rp.policy_id = p.id where r.account_id=\"$acc\" group by role_name order by policy_cant desc limit 15;"
    }
   ]
  },
  {
   "title": "Top Roles with more Trusted Entities  ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select ro.name,\n       count(distinct ta.account_id) + count( distinct tu.user_id) + count(distinct ts.service_id) + count(distinct tr.assuming_role_id) as \"Total\"\nfrom role as ro\n         left join trusted_role_account as ta on ta.role_id = ro.id\n         left join trusted_role_user as tu on tu.role_id = ro.id\n         left join trusted_role_service as ts on ts.role_id = ro.id\n         left join trusted_role_role as tr on tr.role_id = ro.id\nwhere ro.foreign=0 and ro.account_id=\"$acc\"\ngroup by ro.name\norder by Total desc limit 15"
    }
   ]
  },
  {
   "title": "Top services with more Roles",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select service.name as \"Service\", count(distinct role.arn)\nfrom service\n         inner join permission on permission.service_id = service.id\n         inner join policy on policy.id = permission.policy_id\n         inner join role_policy on policy.id = role_policy.policy_id\n        inner join role on role.id = role_policy.role_id\nwhere role.account_id=\"$acc\"\ngroup by service.name\norder by count(distinct role.arn) desc"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Users  ($acc)",
   "type": "stat",
   "description": "Total ammount of policies",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"User count\" from user where account_id=\"$acc\""
    }
   ]
  },
  {
   "title": "Policies in Users ($acc)",
   "type": "stat",
   "description": "Total ammount of policies",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(policy.id)) as \"Policies in Users\" from policy inner join user inner join user_policy on user.id=user_policy.user_id and policy.id=user_policy.policy_id where user.account_id=\"$acc\";"
    }
   ]
  },
  {
   "title": "TOP 15 User with more policies ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select user.name, count(policy.name) as \"Policy in Users\" from user inner join policy inner join user_policy on user.id=user_policy.user_id and policy.id=user_policy.policy_id where user.account_id=\"$acc\" group by user.name order by count(policy.name) desc limit 15;"
    }
   ]
  },
  {
   "title": "TOP 10 Policies attached to Users  ($acc)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select policy.name, count(user.name) as \"Users in Policy\" from policy inner join user inner join user_policy on user.id=user_policy.user_id and policy.id=user_policy.policy_id where user.account_id=\"$acc\" group by policy.name order by count(user.name) desc limit 10;"
    }
   ]
  }
 ]
}